### ISSUE TITLE
Crash report on startup with Destroy-0.1.0-snapshot-5

### ISSUE THREAD

**Issue by Drigonis** [petrolpark/Petrols-Parts#12]
**Description**

Game crashes on startup when paired with Destroy version 0.1.0 snapshot 5.

**To reproduce**

1. Install Petrol Parts latest version and Destroy latest snapshot (snapshot 5).
2. Run the game

**Expected Behavior**

Not crashing, I guess

**System information**

 - Minecraft v1.20.1
 - Create v0.5.1h
 - Destroy v0.1.0-snapshot-5
 - Petrol's Parts v1.0.3
 - Petrolpark's Library v1.0.5

**Comment by petrolpark** [comment]
Wait until Destroy 0.1.0 releases.
