### ISSUE TITLE
[Suggestion] Refrigerstraytors

### ISSUE THREAD

**Issue by emihead** [petrolpark/Petrols-Parts#16]
**Description**

I hope this isn't rude to suggest! I would love to see the Refrigerstraytors from Destroy brought over to this mod, or maybe another mod if they'd be too out of place here.

**Problem This Addresses**

I love Refrigerstraytors and think they add so much when it comes to expanding Create's recipes, especially with their compatibility with base recipe types. I don't think there are any other addons that do anything similar to the Refrigerstraytors, so I feel like there's definitely a niche for them, ESPECIALLY when it comes to custom datapack recipes and mod integration. I know their mechanics are pretty closely integrated with Destroy, so maybe they could get a "simplified" version that accepts certain items like Blaze Burners instead of just fluids.

**Comment by emihead** [comment]
![image](https://github.com/user-attachments/assets/9403361e-3196-4875-adfb-0388ffcabf72)
I'm coming back to this because I did some testing and it turns out cooling just works out of the box with other addon recipe types, despite some minor JEI glitches.
This is so insane and makes me want the Refrigerstraytor in PP even more. It might honestly be worth just getting Destroy and KubeJSing out what doesn't fit in my modpack at this point. What an incredible tool this could be for modpack authors!!

**Comment by FlamingKetchup** [comment]
Refrigerstraytors require Destroy refrigerants and are necessary for some Destroy recipes so putting them in Petrol's Parts doesn't make sense. A new mod with a non-Destroy version of the Refrigerstraytor (fueled with snow or ice or perhaps some coolant fluid made from snow or ice) might make more sense.
