### ISSUE TITLE
petrolsparts only supports destroy 0.1.0

### ISSUE THREAD

**Issue by Umi-io** [petrolpark/Petrols-Parts#19]
**Before submitting a bug report, ensure you are familiar with the [rules](https://github.com/petrolpark/Petrols-Parts/issues/1).** Do not include this line in the bug report.

**Describe the bug**

Petrol's Parts is looking specifically for versions 0.1.0 through 0.1.0 instead of, what I assume is the intended, 0.1.0-snapshot-1 through 0.1.0-snapshot-10

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Construct this set up - destroy-1.20.1-0.1.0-snapshot-10.jar petrolsparts-1.20.1-1.0.3.jar and their dependencies on Forge
3. Use a belt grinder for carbon fiber while the game loads

**Expected Behavior**

Game NOT crashing on startup

**System Information**

 - Create version  0.5.1.j, Create version 0.5.1.f, Create version 0.5.1.h
 - petrolsparts-1.20.1-1.0.3
 - destroy-1.20.1-0.1.0-snapshot-10
 - petrolpark'slibrary-1.20.1-1.0.6
I tried all three

**Additional context**

pastebin, because log too long
https://pastebin.com/CftHVYgp

**Minecraft Username**

Umi_o

**Comment by MadeOfMo1ecules** [comment]
This is known and is mostly because Destroy 0.1.0 has not been fully released yet and the snapshots were not factored into Petrol's Parts's compatibility
