### ISSUE TITLE
Parts invisible in ponder animations

### ISSUE THREAD

**Issue by notpresident35** [petrolpark/Petrols-Parts#2]
The ponder animations for the double cardan shaft, differential, planetary gearset, and colossal cogwheel appear to be failing to render said parts. Note that coaxial cogwheels appear correctly.
![colossal cogwheel appears invisible](https://github.com/user-attachments/assets/3438ddca-d024-4310-ba64-24cc46dd8e35)
![colossal cogwheel appears invisible](https://github.com/user-attachments/assets/764c388e-95e1-48b1-a508-8ded8fef5002)
![double cardan shaft appears invisible](https://github.com/user-attachments/assets/45b514fb-36a8-4d4e-90b0-16b7fae75455)

**Comment by petrolpark** [comment]
Fixed in 1.0.2.
