### ISSUE TITLE
Fabric Compatibility 1.20.1

### ISSUE THREAD

**Issue by Razor9515** [petrolpark/Petrols-Parts#3]
Hey. Are you gonna support Fabric? Would be awseome for our Modpack 👍🏻

**Comment by DadamaldaDad** [comment]
Bruh. People can't read guidelines.

**Comment by adaliszk** [comment]
The guideline you refer to was updated three days ago; before that, it contained nothing. This ticket was raised a week ago before the rules were written... Next time, could you check the edit history and not complain needlessly?

**Comment by DadamaldaDad** [comment]
I apologize. I might have confused days with weeks. I'm very sorry and didn't mean to be harsh or disturb.

**Comment by petrolpark** [comment]
No.
