### ISSUE TITLE
[1.20.1 Neoforge] Crashes when trying to place Colossal Cogwheel with placement helper

### ISSUE THREAD

**Issue by OozyLucy** [petrolpark/Petrols-Parts#4]
How to replicate:

1. Place down a create object that isn't a cogwheel but uses the cogwheel placement helper (Millstone, Display Board, Mechanical Pump)
2. Aim at it with Colossal Cogwheel
3. Instant Crash

Crash report: [crash-2024-09-02_09.44.39-client.txt](https://github.com/user-attachments/files/16838264/crash-2024-09-02_09.44.39-client.txt)

**Comment by petrolpark** [comment]
Fixed in 1.0.3.
