### ISSUE TITLE
Russian language for mod

### ISSUE THREAD

**Issue by rim4oo** [petrolpark/Petrols-Parts#5]
😘😘😘😘🥰🥰
[ru_ru.json](https://github.com/user-attachments/files/16870488/ru_ru.json)

**Comment by VladisCrafter** [comment]
Overall good, but please consider fixing:
1. In `advancement.petrolsparts.coaxial_gear.description` the gear is called "зубчатое колесо" while in other strings it is "шестерня", as intended by base Create mod;
2. **All ponder headers should remain in instrumental case** - that's a logical rule, please try to follow it too;
3. In the ponders, the period at the end of the sentence is placed only at the last one, not at previous ones nor the header;
4. I looked over a Chinese translation, and there the word "parts" in "Petrol's parts" is translated in both advancement root and item group (I'd suggest naming it "Запчасти Petrol'а");
6. In `petrolsparts.ponder.differential.text_10` the word "передает" has "ё" in it.

Thanks for reading and, once again, the translation is mostly good! Have a nice day :]

**Comment by rim4oo** [comment]
Thanks for your comment, I have corrected your comments in this file 
[ru_ru.json](https://github.com/user-attachments/files/16841661/ru_ru.json)

**Comment by rim4oo** [comment]
As I saw, it is not customary for us to translate the name of addons

**Comment by VladisCrafter** [comment]
@rim4oo I'm telling not about the add-on name itself but rather an item group and advancement root which are completely fine to translate :>

**Comment by petrolpark** [comment]
Thank you for the help. In future, submit translations as PRs.

**Comment by petrolpark** [comment]
Added in 1.0.3.
