### ISSUE TITLE
Ponder inconsistancy

### ISSUE THREAD

**Issue by BonezTheWonderful** [petrolpark/Petrols-Parts#7]
When viewing the ponder scene for the colossal cogwheel it states that it moves large cogs at a factor of 3 and small cogs at a factor of 6 but in game this isn't true it still moves them by a factor of 2 
if my wording isnt well understood basically big cog spins at 16 and when connected to others cogs through the colossal cog they spin at 32 rather than 48

**Comment by Catchmons** [comment]
I think it's an easy culculation problem. 
"The colossal cogwheel it states that it moves large cogs at a factor of 3 and small cogs at a factor of 6" It means that the speed of Colossal cog is the **1/3 of the Big cogwheel** it connected to and **the 1/6 of the Small cogwheel**. 
So if you have a Big Cogwheel rotating at **16**, the speed of Colossal cogwheel is **16 * (1/3), equals 16/3**. And the speed of the small cogwheel should be **(16/3) ÷ (1/6), equals 32**.
