### ISSUE TITLE
Compatibility bug w/ extended cogwheels

### ISSUE THREAD

**Issue by kentapainter** [petrolpark/Petrols-Parts#8]
**Situation**
A **change of textures** with the extended cogwheels addon, when using the long shafts the texture is exchanged with the other addon.

Maybe a part of the code takes the same name, or has the same reference of that other addon, and change the texture.

**Forge version**
1.20.1-forge-47.2.23

**Mods 'n Addons**
extendedgears-2.1.1-1.20.1-0.5.1.f-forge
petrolsparts-1.20.1-1.0.2
petrolpark-1.20.1-1.0.1-all
create-1.20.1-0.5.1.f

**screenshots**
![2024-09-05_12 30 10](https://github.com/user-attachments/assets/84e01b7e-853e-4d24-8a08-4a7dea88af30)
![2024-09-05_12 31 23](https://github.com/user-attachments/assets/a6768a1c-ceb6-41ff-ba6a-13b11e8e7fb4)
![2024-09-05_12 32 43](https://github.com/user-attachments/assets/248f2d54-7ac5-43e9-b825-6137a3e44f6c)

Idk if so much information was necessary, but I contributed what I thought could help.
Anyway the **Create: Extended Cogwheel** addon is just decorative, but it would be good to check that, and have those options, maybe in the future to be able to use it to complement this addon.

**Comment by petrolpark** [comment]
The extra information is always useful, thank you. I'm not understanding the issue. Is it that the Shaft gets turned into a Shaftless Cogwheel rather than a Long Shaft?

**Comment by kentapainter** [comment]
exactly !

**Comment by kentapainter** [comment]
> The extra information is always useful, thank you. I'm not understanding the issue. Is it that the Shaft gets turned into a Shaftless Cogwheel rather than a Long Shaft?

exactly !

**Comment by kentapainter** [comment]
My pov change a little, 'cause i need remove the shaftless cogwheel, but you can see on this pic, without the **extended cogwheel** as it originally looked. I mentioned the selector before, because you can see in the previous images that it has a different box. The shaftless one is square, and the long shaft one... cylindrical?

here's the pic
![2024-09-05_13 21 57](https://github.com/user-attachments/assets/34839bad-eb45-40dd-9ade-b9b24abda5ca)

**Comment by petrolpark** [comment]
What's the result of running `/data get block` on the Long Shaft? Does it still happen if you turn off Flywheel instancing (menu -> Create menu -> configs -> configs of other mods -> Flywheel -> Backend, set to OFF)

**Comment by petrolpark** [comment]
Nevermind, this is entirely on [Extended Cogwheel's end](https://github.com/Rabbitminers/Extended-Cogwheels/issues/83).

**Comment by Alastors** [comment]
Fixed on my end, I'm kicking out a few more targeted patches and I'll send it out on the unofficial branch before updating it to 6.0.0

Sorry the original dev never fixed it though.
